name: dbarc_rider
description: "DBARc Rider Flutter Mobile App for Courier & Logistics"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Networking & Storage
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # Hardware & Native Features
  mobile_scanner: ^5.2.3
  signature: ^5.5.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  
  # UI & Styling
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
